spring:
  application:
    name: aquaCore

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/aqua_app
    username: admin
    password: password

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/aqua_app
    user: admin              # ✅ should be 'user', not 'username'
    password: password
    baseline-on-migrate: true

  sql:
    init:
      mode: always

server:
  port: 8086

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
